version: '3.8'

services:
  nginx:
    build:
      context: ./nginx  # Points to the folder with the Nginx Dockerfile
    image: local-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-network

  python-app:
    build:
      context: ./python  # Points to the folder with the Python app Dockerfile
    image: local-python-app
    container_name: python_app
    expose:
      - "8000"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
